services:
  app:
    build: .
    volumes:
      - ./app:/app
# use network_mode OR ports
    network_mode: "host"   
#    ports:
#      - "8888:8888"
#      - "2693:2693/udp"
    user: node
    command: >
      sh -c "yarn install &&
             nodemon --watch /app /app/server.mjs"
